Sync from arcadia/trunk
ydb-platform/ydb-api-protos pull request #13
Opened 2022-12-13 16:45 UTC by asmyasnikov

2022-12-13 17:35 UTC, rekby requested changes
The PR broke public api (some single field like LocationStoragePDisk pdisk = 2 changed to repeatable):
1. Generated code will change and all direct client/sdk must be change they code while update protobuf (and may be change external API - for reflect changes).
2. If old client receive repeated field - messaged will be merged and client can read mess - what wasn't sent by server.
https://developers.google.com/protocol-buffers/docs/encoding#optional

It need additional check about possible broke the monitoring API.

2022-12-14 07:11 UTC, rekby approved these changes

2022-12-14 07:14 UTC, alex268 approved these changes

2022-12-15 16:52 UTC, spuchin approved these changes

2022-12-15 18:25 UTC, merged